Added Progress element docs
Avaiga/taipy-doc pull request #1071
Opened 2024-08-04 17:34 UTC by yaten2302

# Fixes https://github.com/Avaiga/taipy/issues/1464 
# Fixes https://github.com/Avaiga/taipy-doc/issues/1056

2024-08-06 16:23 UTC, FabienLelaquais requested changes
Ok so that's a start.
The point is to create tine example that shows how a given property (or group of related properties) can be used, with what effect.

The progress control is easy enough: only *value*, *linear* and *show_value* have to have their tiny demo.

2024-08-06 16:23 UTC, FabienLelaquais commented on docs/manuals/userman/gui/viselements/generic/progress.md_template
> +## Circular Progress
Ok so typically, every element has its first use case addressed as 'Simple'.
We try to capture how the element will be mostly used. The best is to have as few properties as possible.
In your situation, that would be: only *value* is set.

Note that *render* should not be mentioned: it is used in very rare occasions to hide an element from a page. Not the topic of this documentation page.

2024-08-06 16:23 UTC, FabienLelaquais commented on docs/manuals/userman/gui/viselements/generic/progress.md_template
> +!!! taipy-element
This is useless: *render* is not really a feature of the progress bar, and there's no *value* here, which is mandatory.

2024-08-06 16:23 UTC, FabienLelaquais commented on docs/manuals/userman/gui/viselements/generic/progress.md_template
> +    render=True
```suggestion
```

2024-08-06 16:23 UTC, FabienLelaquais commented on docs/manuals/userman/gui/viselements/generic/progress.md_template
> +    render=True
```suggestion
```

2024-08-07 04:55 UTC, yaten2302 commented
@FabienLelaquais , made the changes 👍 kindly review

2024-08-07 12:57 UTC, FabienLelaquais approved these changes
👍

2024-08-07 12:57 UTC, FabienLelaquais commented on docs/manuals/userman/gui/viselements/generic/progress.md_template
>  !!! taipy-element
So this is useless right?

2024-08-07 15:18 UTC, yaten2302 commented on docs/manuals/userman/gui/viselements/generic/progress.md_template
>  !!! taipy-element
Made the changes @FabienLelaquais 👍

2024-08-10 16:04 UTC, yaten2302 commented
Hey @FabienLelaquais , ig I forgot to add the screenshots in here!! Like, should I create a sample app in taipy and use the `progress` element and then take the ss of the rendered element, right?

2024-08-11 08:06 UTC, FabienLelaquais commented
> use

Don't bother @yaten2302.
I'm the one that usually build these images for users to rapidly evaluate the effects of setting properties.
I spend quite some time trying to come up with very simple example focusing on a tiny set of features.
And I'm very meticulous on this topic - so whatever you provide, I'll certainly have to redo the job... because that's what I feel.

So please do not anything. I will take care of this. Thanks!

2024-08-11 13:16 UTC, merged

2024-08-11 13:40 UTC, yaten2302 commented
Thanks for merging the PR @FabienLelaquais 👍

2024-08-11 14:36 UTC, FabienLelaquais commented
Thanks to you, @yaten2302
There is still some work on this (layout and label management) that we will handle internally because it impacts areas of the implementation such as styling that needs discussions...
So do expect this control to grow a little bit in the next few weeks.

2024-08-11 16:34 UTC, yaten2302 commented
Sure @FabienLelaquais 👍