Fixed documentation for dialog
Avaiga/taipy-doc pull request #1147
Opened 2024-10-03 21:33 UTC by FabienLelaquais

Addresses #1115.

Renamed all references to code examples

2024-10-03 21:55 UTC, FredLL-Avaiga approved these changes
I suppose I'm wrong about taipy-date_range but it looks really weird... I suppose for 5.0 :-)
Well done
Quite a job

2024-10-03 21:55 UTC, FredLL-Avaiga commented on docs/refmans/gui/viselements/generic/date_range.md_template
> +All the date range controls are generated with the "taipy-date_range" CSS class. You can use this
Typo taipy-date_range

2024-10-04 08:12 UTC, namnguyen20999 approved these changes
lgtm

2024-10-04 08:15 UTC, FabienLelaquais commented on docs/refmans/gui/viselements/generic/date_range.md_template
> +All the date range controls are generated with the "taipy-date_range" CSS class. You can use this
Sorry I don't see the typo.

2024-10-04 08:19 UTC, FabienLelaquais commented on docs/refmans/gui/viselements/generic/date_range.md_template
> +All the date range controls are generated with the "taipy-date_range" CSS class. You can use this
Oh.
```suggestion
All the date range controls are generated with the "taipy-date-range" CSS class. You can use this
```

Got it

2024-10-04 08:28 UTC, FredLL-Avaiga requested changes
_ => - in class names

2024-10-04 08:28 UTC, FredLL-Avaiga commented on docs/refmans/gui/viselements/generic/file_download.md_template
> +All the file download controls are generated with the "taipy-file_download" CSS class. You can use this class
_ => -

2024-10-04 08:28 UTC, FredLL-Avaiga commented on docs/refmans/gui/viselements/generic/file_selector.md_template
> +All the file selector controls are generated with the "taipy-file_selector" CSS class. You can use this class
idem

2024-10-04 09:23 UTC, FabienLelaquais commented on docs/refmans/gui/viselements/generic/file_download.md_template
> +All the file download controls are generated with the "taipy-file_download" CSS class. You can use this class
Ok

2024-10-04 09:24 UTC, FabienLelaquais commented on docs/refmans/gui/viselements/generic/file_selector.md_template
> +All the file selector controls are generated with the "taipy-file_selector" CSS class. You can use this class
Ok

2024-10-04 09:31 UTC, FredLL-Avaiga approved these changes
👍

2024-10-04 09:44 UTC, merged