Create a new doc section for filled area plots
Avaiga/taipy-doc pull request #293
Opened 2022-12-11 07:38 UTC by haotran-avaiga

2022-12-11 16:41 UTC, FabienLelaquais requested changes
Great, great work!

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +An area chart displays a solid color between the traces of a graph. It is an option on scatter charts. Areas will be filled according to the ‘fill’ option ("none", "tozeroy", "tozerox" , "tonexty", "
=>
An area chart displays a solid colored area between the traces of a graph.

You can create a filled plot by using a *scatter* chart type, and specifying the `fill` option of the chart *options* dictionary.
This value can be one of "none", "tozeroy", "tozerox" , "tonexty", "tonextx", "toself", and "tonext", as indicated in the [Plotly documentation](https://plotly.com/python/reference/#scatter-fill).

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +This example shows the number of sold items per day (The shop closes on Weekend :) ).
=>
"""
The simplest example is where you have a single dataset to represent.

Here is how we can represent the number of items sold every weekday:
"""

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +import pandas as pd
You don't need Pandas... and we don't want to show the imports anyways.

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +### Basic Overlaid Area Chart
Overlay of area charts

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +## Filled Area Plots
Replace 'Plot' by 'Chart'.

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +With above example, we want to add one more trace to visualize the total price (x 1000$) per day.
=>
You can overlay two different data sets in the same chart. Each data set will be represented by its own plot.

Starting from the example above, we can add the price of the items:

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +data = {
Only keep this new definition of _data_.

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +md = "<|{data}|chart|x=day|y[1]=items|y[2]=prize|type=scatter|options={options}|>"
+HTML

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +It is not perfect, isn't it. So we have to define 2 types of fill option for "items" and "prize"
=>

The problem with that representation is that [blabla]. We can improve the result by specifying two different values for the _fill_ option of the two plots:

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +optionsItem = {"fill": "tozeroy"}
Only keep these two lines

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +md = "<|{data}|chart|x=day|y[1]=items|y[2]=prize|type=scatter|options[1]={optionsItem}|options[2]={optionsPrize}|>"
+HTML

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +Great, it is better now, however we don't want to see the lines.
=>
That is a bit better. However the lines that surround the plots are not looking good. Let us remove them.

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +```py
Remove all the code: it is exactly the same as before (because we don't need the 'mode' variable).

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +md = "<|{data}|chart|x=day|y[1]=items|y[2]=prize|type=scatter|mode={mode}|options[1]={optionsItem}|options[2]={optionsPrize}|>"
=>
<|{data}|chart|x=day|y[1]=items|y[2]=prize|type=scatter|mode=none|options[1]={optionsItem}|options[2]={optionsPrize}|>

+HTML

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +![Basic Overlaid Area Chart without boundary lines](filled-area-overlaid-3.png)
Insert:

Note how the settingof the _mode_ property_ to "none"has removed the surrounding lines.

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +### Simple example
Please skip a line after a title definition. For clarity and homogeneity.

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +### Stacked Area Chart
Please skip a line after a title definition. For clarity and homogeneity.

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +A stacked area chart is a variation of an area chart. It visualized the evolution of multiple data series (value of several groups) over time.
Excellent!

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +mode = "none"
No need for a variable here.

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +md = "<|{data}|chart|x=month|y[1]=milk|y[2]=bread|y[3]=apples|type=scatter|mode={mode}|options[1]={options4Milk}|options[2]={options4Bread}|options[3]={options4Apples}|>"
+HTML
Maybe shorter variable names? 
Like 
   opts_milk, opts_bread...

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +A percentage stacked area chart is very close to a classic stacked area chart. However, values are normalised to make in sort that the sum of each group is 100 at each position on the X axis
Final dot.

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +md = "<|{data}|chart|x=region|y[1]=usa|y[2]=china|y[3]=eu|y[4]=africa|type=scatter|options[1]={options4USA}|options[2]={options4China}|options[3]={options4EU}|options[4]={options4Africa}|layout={layo
+HTML

2022-12-11 16:41 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +![Normalized Stacked Area Chart](filled-area-stacked-2.png)
Please explain what happened. What made the magic happened?

2022-12-13 14:21 UTC, haotran-avaiga commented on docs/manuals/gui/viselements/charts/filled-area-plots.md
> +![Normalized Stacked Area Chart](filled-area-stacked-2.png)
Sorry, I can't catch you here. the magic is 
- Percent calculator
- Or the popup appeared after hovering at a point?

2023-01-11 16:48 UTC, FabienLelaquais approved these changes

2023-01-11 16:57 UTC, FredLL-Avaiga approved these changes

2023-01-11 16:57 UTC, FredLL-Avaiga commented on docs/manuals/gui/viselements/charts/filled-area.md
> +| [*type*](../chart.md#p-type)      | `bar`          |  |
scatter ?

2023-01-11 16:58 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/charts/filled-area.md
> +| [*type*](../chart.md#p-type)      | `bar`          |  |
😒Thx!

2023-01-11 17:00 UTC, merged