feature/#393 added doc for return type of submit methods
Avaiga/taipy-doc pull request #396
Opened 2023-03-01 02:50 UTC by toan-quach

2023-03-02 10:09 UTC, FabienLelaquais approved these changes
👌simple enough.
So `submit()` can return a `Job`, or a list of `Job` instances right?

2023-03-02 10:38 UTC, toan-quach commented
@FabienLelaquais 
Yes, a Job (Task), a list of Jobs (Pipeline), or a dictionary of {pipelineId: [Jobs]} (Scenario)

2023-03-06 09:49 UTC, jrobinAV requested changes
We found an inconsistency with the submission of pipelines/scenarios:

https://github.com/Avaiga/taipy-core/issues/494
The bug fix include a change in the return type of the submit methods.
- `tp.submit(entity)` always returns a list of jobs.
- `scenario.submit()` returns a list of jobs.
- `pipeline.submit()` always returns a list of jobs.
- `task.submit()` returns a job.

The documentation should consider the fix.

2023-03-13 15:29 UTC, jrobinAV commented on docs/manuals/core/entities/scheduling-and-job-execution.md
> +To execute a scenario, you need to call the `taipy.submit()^` method, which will return a list of created `Job^`:
```suggestion
To execute a scenario, you need to call the `taipy.submit()^` method. It returns a list of created `Job^`s:
```

2023-03-13 15:29 UTC, jrobinAV commented on docs/manuals/core/entities/scheduling-and-job-execution.md
> +return a list of created `Job^`:
```suggestion
It is also possible to submit a single pipeline using the same `taipy.submit()^` method. . It returns a list of created `Job^`s:
```

2023-03-13 15:29 UTC, jrobinAV commented on docs/manuals/core/entities/scheduling-and-job-execution.md
> +You can also submit a single task with the same `taipy.submit()^` method, and it will return the created `Job^`:
```suggestion
You can also submit a single task with the same `taipy.submit()^` method. It returns the created `Job^`:
```

2023-03-15 14:39 UTC, jrobinAV approved these changes

2023-03-15 14:42 UTC, merged