Deploy on Databricks
Avaiga/taipy-doc pull request #476
Opened 2023-06-09 14:42 UTC by florian-vuillemot

#420

2023-06-13 14:43 UTC, jrobinAV approved these changes
I believe it s good enough!
We may ask a tech writer to improve it later.

2023-06-14 13:36 UTC, FabienLelaquais requested changes
👍

2023-06-14 13:36 UTC, FabienLelaquais commented on mkdocs.yml_template
> +            - On local machine:
On local machine => On the local machine

2023-06-14 13:36 UTC, FabienLelaquais commented on docs/manuals/run-deploy/deploy/databricks/index.md
> +Databricks is a standard platform for data scientists and big data engineers. It can provide a web-based laptop connected to your data source within your cloud provider. Nevertheless, Databricks does
"web-based laptop"??

"...application in your Databricks"
=>
"application in your Databricks environment"

"cloud provider" -> "Cloud provider" (? not too sure... and if yes, everywhere in this document)

2023-06-14 13:36 UTC, FabienLelaquais commented on docs/manuals/run-deploy/deploy/databricks/index.md
> +    If you don't have a Linux-based machine, you can use a cloud provider as Azure to
"provider as Azure" => "provider like Microsoft Azure"

2023-06-14 13:36 UTC, FabienLelaquais commented on docs/manuals/run-deploy/deploy/databricks/index.md
> +Connect to Databricks and run the previous code in a Databricks Notebook. You should obtain a similar output:
"You should obtain a similar output"
=>
"You should obtain an output similar to the following"

2023-06-14 13:36 UTC, FabienLelaquais commented on docs/manuals/run-deploy/deploy/databricks/index.md
> +In the end, the browser sends a request to the Nginx on the Linux-based machine; the Nginx will redirect
"the Nginx" => "Nginx" (twice)

2023-06-14 13:36 UTC, FabienLelaquais commented on docs/manuals/run-deploy/deploy/databricks/index.md
> +Here is the technical architecture of the solution.
Final '.' => ":'"

2023-06-14 13:36 UTC, FabienLelaquais commented on docs/manuals/run-deploy/deploy/databricks/index.md
> +    The Linux-based machine should be accessible from your network and Databricks.
"from your network and Databricks" => "from your network and from Databricks"

2023-06-14 13:36 UTC, FabienLelaquais commented on docs/manuals/run-deploy/deploy/databricks/index.md
> +Once configured, Nginx will redirect all incoming requests on the port HTTP (80) to port 8080.
"on the port HTTP (80)" => "from the default HTTP port (80)"

2023-06-14 13:36 UTC, FabienLelaquais commented on docs/manuals/run-deploy/deploy/databricks/index.md
> +the redirection by putting the following content in `/etc/nginx/sites-enabled/default` :
"by putting the following" => "by copying the following"

2023-06-14 13:36 UTC, FabienLelaquais commented on docs/manuals/run-deploy/deploy/databricks/index.md
> +Open Databricks on a first tab, and go to compute and select your cluster.
"on a first tab" => "in a first tab"

"and go to compute" => "press "Compute"" (?)

2023-06-14 13:36 UTC, FabienLelaquais commented on docs/manuals/run-deploy/deploy/databricks/index.md
> +Specifically, it forwards all packets from port 8080 to port 5000 on your Databricks.
"your Databricks" => "your Databricks environment" (?)

2023-06-14 13:36 UTC, FabienLelaquais commented on docs/manuals/run-deploy/deploy/databricks/index.md
> +Therefore, running `curl localhost:8080` should get your application's output still running on your Databricks notebook!
"Therefore, running" => "Running"
"still" => "while"

2023-06-14 13:36 UTC, FabienLelaquais commented on mkdocs.yml_template
> +            - On local machine:
Please bring back the double quotes here! Like it is done in the entirety of this template.
We may need to parse this file
Thx

2023-06-14 15:01 UTC, florian-vuillemot commented on docs/manuals/run-deploy/deploy/databricks/index.md
> +Specifically, it forwards all packets from port 8080 to port 5000 on your Databricks.
The "Databricks environment notebook" is a bit strange for me.

2023-06-14 16:28 UTC, FabienLelaquais approved these changes
👍

2023-06-14 16:28 UTC, FabienLelaquais commented on docs/manuals/run-deploy/deploy/databricks/index.md
> +Specifically, it forwards all packets from port 8080 to port 5000 on your Databricks.
Indeed.
But "it forwards all packets from port 8080 to port 5000 on your Databricks." is really strange as well.
What is "your Databricks"?

2023-06-14 16:28 UTC, jrobinAV approved these changes
We should ask the CS team/tech writer to improve the diagrams. Meanwhile that s good to be merge for me.

2023-06-14 16:30 UTC, merged