Doc/Core#693 - Remove clean_entities attribute from CoreSection
Avaiga/taipy-doc pull request #519
Opened 2023-08-02 06:49 UTC by trgiangdo

https://github.com/Avaiga/taipy-core/issues/693

2023-08-02 11:39 UTC, erikfTW requested changes

2023-08-02 11:39 UTC, erikfTW commented on docs/manuals/core/config/core-config.md
>    repository.
```suggestion
  `filesystem`, `sql` and `mongo`. The filesystem will be used as the default repository if no repository type is informed.
```

2023-08-02 11:39 UTC, erikfTW commented on docs/manuals/core/versioning/configuration.md
> +with the version number is "0.1".
```suggestion
with the version number "0.1".
```

2023-08-02 11:39 UTC, erikfTW commented on docs/manuals/core/versioning/configuration.md
>    the configuration has changed and run the application. Default to False.
```suggestion
  the configuration has changed and runs the application. Default to False.
```

2023-08-02 11:39 UTC, erikfTW commented on docs/manuals/core/versioning/configuration.md
>  !!! note "Configure using both TOML file and CLI options"
```suggestion
!!! note "Configure using both the TOML file and CLI options."
```

2023-08-02 11:39 UTC, erikfTW commented on docs/manuals/core/versioning/experiment_mode.md
>  As you can see, this time the number of scenarios displayed is 2. Indeed, we run the "0.1" version
```suggestion
As you can see, this time, the number of scenarios displayed is 2. Indeed, we run the "0.1" version
```

2023-08-02 11:39 UTC, erikfTW commented on docs/manuals/core/versioning/experiment_mode.md
>      you can ensure your code is compatible with both versions of data nodes.
```suggestion
    Hint: You can migrate your old entities to become compatible with the new configuration or
    ensure your code is compatible with both versions of data nodes.
```

2023-08-02 11:39 UTC, erikfTW commented on docs/manuals/core/versioning/experiment_mode.md
> +Successfully delete version 0.1 from the production version list.
```suggestion
Successfully deleted version 0.1 from the production version list.
```

2023-08-03 08:25 UTC, jrobinAV approved these changes

2023-08-03 08:27 UTC, jrobinAV approved these changes

2023-08-03 08:27 UTC, jrobinAV commented on docs/relnotes.md
> +- The `clean_entities` attribute has been removed from the `CoreSection^`. Correspondingly, the
```suggestion
- The `clean_entities` attribute has been removed from the `GlobalAppConfig^`. Correspondingly, the
```

2023-08-03 08:28 UTC, trgiangdo commented on docs/relnotes.md
> +- The `clean_entities` attribute has been removed from the `CoreSection^`. Correspondingly, the
the `clean_entities` attribute belongs to CoreSection, not the GlobalAppConfig though.

2023-08-03 08:36 UTC, erikfTW approved these changes

2023-08-03 08:47 UTC, merged

2023-08-03 13:55 UTC, jrobinAV commented on docs/relnotes.md
> +- The `clean_entities` attribute has been removed from the `CoreSection^`. Correspondingly, the
In previous versions like 2.4 the clean_entities was part of GlobalAppConfig, no?

2023-08-03 14:16 UTC, trgiangdo commented on docs/relnotes.md
> +- The `clean_entities` attribute has been removed from the `CoreSection^`. Correspondingly, the
Actually no, it was part of the CoreSection.

2023-08-03 17:08 UTC, jrobinAV commented on docs/relnotes.md
> +- The `clean_entities` attribute has been removed from the `CoreSection^`. Correspondingly, the
OK, I must be confused... Let s forget about my suggestion then.