Doc/Template#20 - Implement the default template
Avaiga/taipy-doc pull request #525
Opened 2023-08-18 06:28 UTC by trgiangdo

https://github.com/Avaiga/taipy-templates/issues/20

2023-08-18 09:49 UTC, erikfTW requested changes

2023-08-18 09:49 UTC, erikfTW commented on docs/manuals/cli/create.md
> +How many pages and the name of the pages? [1]: 3 slide_1 slide_2 slide_3
```suggestion
How many pages, and the name of the pages? [1]: 3 slide_1 slide_2 slide_3
```

2023-08-18 09:49 UTC, erikfTW commented on docs/manuals/cli/create.md
> +minimalized Taipy application.
```suggestion
In this example, we scaffold a new application using the default Taipy template, which lets us create a simple,
minimalized Taipy application.
```

2023-08-18 09:49 UTC, erikfTW commented on docs/manuals/cli/create.md
> +  In the prompt, we can see the question along with the default value in the square brackets.
```suggestion
  In the prompt, we can see the question and the default value in the square brackets.
```

2023-08-18 09:49 UTC, erikfTW commented on docs/manuals/cli/create.md
> +  We can either provide an answer or just press enter to use the default value.
```suggestion
  We can provide an answer or press enter to use the default value.
```

2023-08-18 09:49 UTC, erikfTW commented on docs/manuals/cli/create.md
> +- In the first question, we define the application root folder as "new_application"
```suggestion
- The first question defines the application root folder as "new_application"
```

2023-08-18 09:49 UTC, erikfTW commented on docs/manuals/cli/create.md
> +- In the second and third questions, we set the main Python file of the application as "app.py" and the title of the web page as "App Title".
```suggestion
- In the second and third questions, we set the main Python file of the application as "app.py" and the web page's title as "App Title".
```

2023-08-18 09:49 UTC, erikfTW commented on docs/manuals/cli/create.md
> +- In the 4th question, we clarify that we want a Taipy multi-page GUI application, with the page names "slide_1", "slide_2", and "slide_3". Please note that if the names are not clarified, the defaul
```suggestion
- In the 4th question, we clarify that we want a Taipy multi-page GUI application with the page names "slide_1", "slide_2", and "slide_3". Please note that if the names are not clarified, the default name will be "page_1", "page_2", and so on.
```

2023-08-18 09:49 UTC, erikfTW commented on docs/manuals/cli/create.md
> +Finally, we change the directory (`cd`) to our newly created folder and start the application by running `python app.py`.
```suggestion
Finally, we changed the directory (`cd`) to our newly created folder and started the application by running `python app.py`.
```

2023-08-18 09:49 UTC, erikfTW commented on docs/manuals/cli/create.md
>  You can also specify another template using the `--template` option.
```suggestion
You can specify another template using the `--template` option.
```

2023-08-18 09:49 UTC, erikfTW commented on docs/relnotes.md
> +- The "taipy-default-template" template now also supports creating a multi-pages application with Core and Rest services.
```suggestion
- The "taipy-default-template" template also supports creating a multi-pages application with Core and Rest services.
```

2023-08-18 09:49 UTC, erikfTW commented on docs/relnotes.md
> +  a Taipy multi-pages application.
```suggestion
- The "multi-page-gui" template has been removed. Please use the "taipy-default-template" instead to create
  a Taipy multi-pages application.
```

2023-08-21 07:01 UTC, erikfTW approved these changes

2023-08-23 14:53 UTC, jrobinAV approved these changes

2023-08-24 07:42 UTC, merged