first draft for new GS
Avaiga/taipy-doc pull request #557
Opened 2023-09-15 14:34 UTC by jrobinAV

Here is a proposal for the new getting started content. 

- I tried to be short and direct in both the content and the style, but it can undoubtedly be improved.
- We can also improve the style, creating a better graphic for the DAG, better screenshots, etc...

Please review the English, the form, the content, and the style

![image](https://github.com/Avaiga/taipy-doc/assets/88036007/501d15a6-2e02-4ea4-a7be-6575f38cd1d9)
![image](https://github.com/Avaiga/taipy-doc/assets/88036007/421c29cc-62a0-4e53-8e2c-58fcec0e1b2b)
![image](https://github.com/Avaiga/taipy-doc/assets/88036007/3a5f571e-babe-4eca-8826-873917bb61f9)
![image](https://github.com/Avaiga/taipy-doc/assets/88036007/fbef4817-4a13-4837-87e3-b8147177d65f)
![image](https://github.com/Avaiga/taipy-doc/assets/88036007/04ecc27e-6f23-459a-8a32-ae7348eb6e27)

2023-09-15 14:54 UTC, FabienLelaquais approved these changes
Minor optional comments

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/hello_world.py
> +#                  Configure your application                  #
I would have said "THE" application

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/hello_world.py
> +#                     Design your interface                    #
THE user interface

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/hello_world.py
> +    #            Instantiate the Core service and run it           #
=> Instantiate and run the Core service

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/hello_world.py
> +    #               Manage your scenarios and data nodes           #
I see the idea in manage.
What about: Create the data flow?

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/hello_world.py
> +    #            Instantiate the Gui service and run it            #
Instantiate and run the Gui service

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/hello_world_scenario.py
> +import taipy as tp
Same comment as in hello_world.py

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +!!! info "Other Installation Options"
=> "Other installation options"

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +- Line 10 configures a task named *build_msg* associated with the `build_message()`
=> \*build_message()\*

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +  function, specifying input and output data nodes.
"specifying input" -> "specifying the input"

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +Running the Core service allows Taipy to process the configuration made in the
The Core service "processes the configuration made in the  previous step"?

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +### Creating Scenarios and accessing data
No capital to Scenarios

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +Now that Taipy Core service is running, you can create and manage scenarios, submit
"that Taipy Core service" -> "that the Taipy Core service"

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +
You may want to remove those two empty lines.
The code snippet is attached to the paragraph before.

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +``` python linenums="1"
The convention you use basically everywhere is not to have this white space after the three backticks

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +`hello_scenario` from the scenario configuration built before.
\*hello_scenario\*

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +Line 4, sets the input data node *input_name* of `hello_scenario` with the string
same

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +value "Taipy" using the write() method.
\`write()\`

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +Line 5 submits the `hello_scenario` for execution, which triggers the creation
same

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +to the `build_message()` function, and writes the result to the output data node.
same
... then in the rest of the text body.

Only API elements should have a fixed size font.

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +Putting all together the pieces, here is the Python code corresponding to the example:
"here is the Python code corresponding to the example" -> "you can download the entire Python code for the example from \[this link\]\(hello_world_scenario.py\)"

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +And here is the expected output.
"output." -> "output:"

2023-09-15 14:54 UTC, FabienLelaquais commented on docs/getting_started-new/index.md
> +<a href="./hello_world.py" download>`hello_world.py`</a>
same as above.

2023-09-15 15:28 UTC, FlorianJacta approved these changes

2023-09-15 15:28 UTC, FlorianJacta commented on docs/getting_started-new/hello_world.py
> +    state.hello_scenario.submit(wait=True)
`wait=True` is not necessary

2023-09-15 19:19 UTC, erikfTW requested changes

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/hello_world.py
> +#                  Configure your application                  #
Can be even: Configure application.

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/hello_world.py
> +# The scenario represent the whole execution graph
```suggestion
# The scenario represents the whole execution graph
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/hello_world.py
> +    #            Instantiate the Core service and run it           #
or maybe: Create the Core service and start it.

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/hello_world.py
> +    #               Manage your scenarios and data nodes           #
```suggestion
    #               Manage scenarios and data nodes           #
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/hello_world.py
> +    #            Instantiate the Gui service and run it            #
here as well maybe: Create the GUI service and start it.

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/index.md
> +and building your first application.
```suggestion
Welcome to Taipy! This guide will show you how to install Taipy 
and create your first application.
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/index.md
> +install the latest stable release of Taipy.
```suggestion
To begin with Taipy, ensure you have Python installed (version 3.8 or higher) along with
[pip](https://pip.pypa.io) on your system. Once you have these prerequisites, 
open your terminal or command prompt and run the following command to get the latest stable version of Taipy downloaded and installed:
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/index.md
> +    for additional instructions.
```suggestion
    You can find additional instructions on the [installation page](installation/index.md) 
    if you require different ways to install Taipy or don't have Python or pip installed.
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/index.md
> +can be as simple or as complex as your needs require.
```suggestion
Acyclic Graph (DAG), where tasks (or functions) exchange data. You can make your 
scenario as easy or as complicated as you want, depending on what you need.
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/index.md
> +(orange box):
```suggestion
For your first scenario, we'll make a straightforward "Hello World" example 
to show you how the setup works. Here's a picture of the
scenario's execution graph, which has two data nodes (blue boxes) and one task 
(orange box):
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/index.md
> +data node named *message*.
```suggestion
This involves a single input data node called *name*.  Afterward, a task called 
*build_message* takes the first initial data node and produces a second  
data node called *message*.
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/index.md
> +- Lines 4-5 define the function that the task will use during execution.
```suggestion
- Lines 4-5 define the task's function during execution.
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/index.md
> +Line 3 is standard boilerplate code to ensure that your script runs only from the
```suggestion
Line 3 is standard boilerplate code to ensure your script runs only from the 
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/index.md
> +In line 4, we simply instantiate and run a Core service.
```suggestion
In line 4, we instantiate and run a Core service.
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/index.md
> +these actions:
```suggestion
With the Taipy Core service up and running, you have the ability to create and manage scenarios, submit 
task graphs for execution, and access data nodes. Here's a code snippet to illustrate  
these actions:
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/index.md
> +Line 6 reads and prints the output data node `message` that has been written by
```suggestion
Line 6 reads and prints the output data node `message` written by 
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/index.md
> +by end-user actions in a graphical interface built using Taipy.
```suggestion
This interaction is typically integrated into Python functions that get triggered
by end-user actions in a graphical interface built using Taipy. 
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/index.md
> +created before. Use the following Python code :
```suggestion
In this section, we suggest a simple graphical interface for interacting with the previously created 
scenario. Use the following Python code:
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/index.md
> +corresponding to the example:
```suggestion
Combining both the scenario and the GUI components, here's the full Python code 
for the example:
```

2023-09-15 19:19 UTC, erikfTW commented on docs/getting_started-new/index.md
> +use cases and advanced features, refer to the
```suggestion
That covers the fundamental steps to begin with Taipy. For more realistic 
use cases and advanced features, refer to 
```

2023-09-17 10:32 UTC, vhfgosselin commented
Ok I will look into it but usually our competitors provide more
explanations about setting it using ends and differentenvs. For instance:
https://docs.streamlit.io/library/get-started/installation


On Fri 15 Sep 2023 at 16:34, Jean-Robin ***@***.***> wrote:

> Here is a proposal for the new getting started content.
>
>    - I tried to be short and direct in both the content and the style,
>    but it can undoubtedly be improved.
>    - We can also improve the style, creating a better graphic for the
>    DAG, better screenshots, etc...
>
> Please review the English, the form, the content, and the style
>
> [image: image]
> <https://user-images.githubusercontent.com/88036007/268311426-501d15a6-2e02-4ea4-a7be-6575f38cd1d9.png>
> [image: image]
> <https://user-images.githubusercontent.com/88036007/268311667-421c29cc-62a0-4e53-8e2c-58fcec0e1b2b.png>
> [image: image]
> <https://user-images.githubusercontent.com/88036007/268311787-3a5f571e-babe-4eca-8826-873917bb61f9.png>
> [image: image]
> <https://user-images.githubusercontent.com/88036007/268311929-fbef4817-4a13-4837-87e3-b8147177d65f.png>
> [image: image]
> <https://user-images.githubusercontent.com/88036007/268312044-04ecc27e-6f23-459a-8a32-ae7348eb6e27.png>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Avaiga/taipy-doc/pull/557
> Commit Summary
>
>    - 4bf8963
>    <https://github.com/Avaiga/taipy-doc/pull/557/commits/4bf89634d93215321bf98447e8b3015bd9b91fa5>
>    first draft for new GS
>    - 292acbb
>    <https://github.com/Avaiga/taipy-doc/pull/557/commits/292acbb93048b45c702105573772a7c3178d1754>
>    add title into Installation page
>    - 9d534f0
>    <https://github.com/Avaiga/taipy-doc/pull/557/commits/9d534f02063ba12927507ef4e0bcd30111ce8c6e>
>    remove nav for installation page
>    - ef2350e
>    <https://github.com/Avaiga/taipy-doc/pull/557/commits/ef2350e329f7d8c02f2a0b53933300baba588886>
>    remove nav for GS page
>    - d30d0b2
>    <https://github.com/Avaiga/taipy-doc/pull/557/commits/d30d0b2c59bad2099471a43c45b5639866e4d8a1>
>    tune GS
>    - 1db8411
>    <https://github.com/Avaiga/taipy-doc/pull/557/commits/1db8411f973be63b13b8d5f95d2c8d55ebebd469>
>    small improvements
>    - d44c178
>    <https://github.com/Avaiga/taipy-doc/pull/557/commits/d44c178f83bea1c16d2d969ac34e3602e07efd18>
>    add screenshot
>
> File Changes
>
> (8 files <https://github.com/Avaiga/taipy-doc/pull/557/files>)
>
>    - *D* docs/getting_started-new/hello-world.md
>    <https://github.com/Avaiga/taipy-doc/pull/557/files#diff-e1ce5d8cca20d10a0097245a931410038e8362d8d02a76acbb43840d1bf54c61>
>    (127)
>    - *A* docs/getting_started-new/hello_world.py
>    <https://github.com/Avaiga/taipy-doc/pull/557/files#diff-258158def932d25a29f54dba42d821f97255b35e27ddc521bf848da91b77cab7>
>    (61)
>    - *A* docs/getting_started-new/hello_world.svg
>    <https://github.com/Avaiga/taipy-doc/pull/557/files#diff-c2de8249413b22599e5647c174262166e4021e56c4f79bc3bb952112a4bdaeff>
>    (1)
>    - *A* docs/getting_started-new/hello_world_scenario.py
>    <https://github.com/Avaiga/taipy-doc/pull/557/files#diff-6baeff214c67dcda1e6159cb6ad85665e0785b34618f85e292d6ae5b156b9439>
>    (36)
>    - *M* docs/getting_started-new/index.md
>    <https://github.com/Avaiga/taipy-doc/pull/557/files#diff-d57ea98bd52570236b5989b97e168e4b1598b85cd4d8914ef20c321d6b2b34cc>
>    (181)
>    - *A* docs/getting_started-new/result.png
>    <https://github.com/Avaiga/taipy-doc/pull/557/files#diff-3f58107f01dc9c8b550cb0248028e8b4f93200d216cecaa92923484941c07a86>
>    (0)
>    - *R* docs/installation/index.md
>    <https://github.com/Avaiga/taipy-doc/pull/557/files#diff-1bd22fe42e71efeb0c3a978723e96356c854100e260d7c21ad64b325e5e2271f>
>    (5)
>    - *M* mkdocs.yml_template
>    <https://github.com/Avaiga/taipy-doc/pull/557/files#diff-7267b243fd7af7fbfaec25568b5500f2686c1e58af8b6c901ed6c8f8924ff003>
>    (4)
>
> Patch Links:
>
>    - https://github.com/Avaiga/taipy-doc/pull/557.patch
>    - https://github.com/Avaiga/taipy-doc/pull/557.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Avaiga/taipy-doc/pull/557>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE6OHST3HHNL3XVDP547XS3X2RRPJANCNFSM6AAAAAA4Z5EC3I>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-09-17 13:18 UTC, merged