doc/kb/tips/skippable_tasks/index
Avaiga/taipy-doc pull request #621
Opened 2023-10-08 13:12 UTC by erikfTW

This PR includes the skippable tasks tip.

Here we have the original tips:

- [Skippable tasks](https://www.taipy.io/tips/the-skippable-tasks/)

2023-10-08 14:14 UTC, jrobinAV requested changes

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +```python linenums="1"
When the code is not explained line by line, or when no line is referred to in the text, we don't need to set the line number.
```suggestion
```python
```

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +documentation for more details on [Data nodes](https://www.taipy.io/tips/the-data-nodes/).
Please use a relative path to the documentation version of the tip.

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +<iframe width="640" height="360" src="https://www.taipy.io/wp-content/uploads/2023/04/full_config.mp4?_=1" frameborder="0" allowfullscreen></iframe>
Can we host this file on taipy doc?

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +```python linenums="1"
When the code is not explained line by line, we don't need to set the line number.

```suggestion
```python
```

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +```python linenums="1"
same remark

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +![Leveraging Skippability in Taipy Tasks](skippable_tasks_4.png){width=100%}
Please replace picture by console block.

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +![Leveraging Skippability in Taipy Tasks](skippable_tasks_5.png){width=100%}
Please replace picture by console block.

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +```python linenums="1"
Same remark

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +```python linenums="1"
Same remark

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +![Leveraging Skippability in Taipy Tasks](skippable_tasks_6.png){width=100%}
Same remark

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +<iframe width="640" height="360" src="https://www.taipy.io/wp-content/uploads/2023/03/predict.mp4?_=3" frameborder="0" allowfullscreen></iframe>
Same remark

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +```python linenums="1"
Same remark

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +```python linenums="1"
Same remark

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +scenario_cfg = Config.configure_scenario_from_tasks(&amp;amp;amp;quot;scenario&amp;amp;amp;quot;, [task_cfg])
The code formatting has been messed up. Please remove special characters.

Plus can you replace `configure_sceanrio_from_task` by `configure_scenario`. This is the new name in the version 3 to be released soon.

```suggestion
from taipy.config import Config
model_cfg = Config.configure_data_node("model", default_path="model.p")
predictions_cfg = Config.configure_data_node("predictions")
task_cfg = Config.configure_task("task", predict, model_cfg, predictions_cfg)
scenario_cfg = Config.configure_scenario("scenario", [task_cfg])
```

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +<iframe width="640" height="360" src="https://www.taipy.io/wp-content/uploads/2023/04/skippable.mp4?_=2" frameborder="0" allowfullscreen></iframe>
same remark

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +print(&amp;amp;amp;quot;Results (sum):&amp;amp;amp;quot;, scenario.sum.read())
Please clean the string code.

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +print(&amp;amp;amp;quot;Results (sum):&amp;amp;amp;quot;,scenario.sum.read())
Please clean the string code.

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +print(&amp;amp;amp;quot;Results (sum):&amp;amp;amp;quot;, scenario.sum.read())
Please clean the string code.

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +scenario_cfg = Config.configure_scenario_from_tasks(&amp;amp;amp;quot;scenario&amp;amp;amp;quot;, [task_cfg])
Same remark on the string code that is messed up + same remark on configure_scenario_from_tasks

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +print(&amp;amp;amp;quot;Results (sum):&amp;amp;amp;quot;, scenario_1.sum.read())
Please clean the string code.

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +![Using Global Data Nodes](skippable_tasks_7.png){width=100%}
Please replace the picture by console code block

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +![Using Global Data Nodes](skippable_tasks_8.png){width=100%}
Please replace the picture by console code block

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +print(&amp;amp;amp;quot;Results (sum):&amp;amp;amp;quot;, scenario_2.sum.read())
Please clean the string code.

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +```python linenums="1"
Same remark

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +![Using Global Data Nodes](skippable_tasks_9.png){width=100%}
Please replace the picture by console code block

2023-10-08 14:14 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +Taipy reuses the existing Data nodes and skips the Task if the input Data nodes have not changed.
```suggestion
Taipy skips the Task if the input Data nodes have not changed and reuses the existing output's Data.
```

2023-10-08 18:30 UTC, FabienLelaquais approved these changes
Typography conventions

2023-10-08 18:30 UTC, FabienLelaquais commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +One of the key features of Taipy's back-end is skippable tasks, which can be skipped under specific conditions.
skippable -> \*skippable\*

2023-10-08 18:30 UTC, FabienLelaquais commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +<iframe width="640" height="360" src="https://www.taipy.io/wp-content/uploads/2023/04/full_config.mp4?_=1" frameborder="0" allowfullscreen></iframe>
I hope so!!

2023-10-08 18:30 UTC, FabienLelaquais commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +In this example, the **multiply_and_add()** function takes two parameters (**nb1** and **nb2**).
Functions and variables use \* everywhere and not \*\*. 
This also happens somewhere above this files.
Please homogenize.

2023-10-08 18:30 UTC, FabienLelaquais commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +Skippability is an optional setting that you can enable when configuring a Task.
Break line. Add \<br/\>

2023-10-08 18:30 UTC, FabienLelaquais commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +Let’s take the previous execution graph and set **skippable=True** to our Task.
"\*\*skippable=True\*\*" -> "\`skippable=True\`"

2023-10-08 18:30 UTC, FabienLelaquais commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +- You can manually update it by writing: `<Data node>.write(…)`.
A link to `DataNode.write()` would I guess be nice...

2023-10-09 19:18 UTC, erikfTW commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +<iframe width="640" height="360" src="https://www.taipy.io/wp-content/uploads/2023/04/full_config.mp4?_=1" frameborder="0" allowfullscreen></iframe>
Let me try it! :)

2023-10-09 19:33 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +scenario_cfg = Config.configure_scenario_from_tasks(&amp;amp;amp;quot;scenario&amp;amp;amp;quot;, [task_cfg])
```suggestion
model_cfg = Config.configure_data_node("model", default_path="model.p")
predictions_cfg = Config.configure_data_node("predictions")
task_cfg = Config.configure_task("task", predict, model_cfg, predictions_cfg)
scenario_cfg = Config.configure_scenario_from_tasks("scenario", [task_cfg])
```

2023-10-09 19:33 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +                                  output=[sum_cfg, product_cfg], skippable=True)
```suggestion
task_cfg = Config.configure_task("multiply_and_add",
                                  function=multiply_and_add,
                                  input=[nb_1_cfg, nb_2_cfg],
                                  output=[sum_cfg, product_cfg], skippable=True)
```

2023-10-09 19:33 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +print(&amp;amp;amp;quot;Results (sum):&amp;amp;amp;quot;, scenario.sum.read())
```suggestion
print("Results (sum):", scenario.sum.read())
```

2023-10-09 19:33 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +print(&amp;amp;amp;quot;Results (sum):&amp;amp;amp;quot;,scenario.sum.read())
```suggestion
print("Results (sum):", scenario.sum.read())
```

2023-10-09 19:33 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +print(&amp;amp;amp;quot;Results (sum):&amp;amp;amp;quot;, scenario.sum.read())
```suggestion
print("Results (sum):", scenario.sum.read())
```

2023-10-09 19:33 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +scenario_cfg = Config.configure_scenario_from_tasks(&amp;amp;amp;quot;scenario&amp;amp;amp;quot;, [task_cfg])
```suggestion
model_cfg = Config.configure_data_node("model",  default_path="model.p")
predictions_cfg = Config.configure_data_node("predictions")
task_cfg = Config.configure_task("task", predict, model_cfg, predictions_cfg)
scenario_cfg = Config.configure_scenario_from_tasks("scenario", [task_cfg])
```

2023-10-09 19:33 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +print(&amp;amp;amp;quot;Results (sum):&amp;amp;amp;quot;, scenario_1.sum.read())
```suggestion
print("Results (sum):", scenario_1.sum.read())
```

2023-10-09 19:33 UTC, jrobinAV commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +print(&amp;amp;amp;quot;Results (sum):&amp;amp;amp;quot;, scenario_2.sum.read())
```suggestion
print("Results (sum):", scenario_2.sum.read())
```

2023-10-09 20:40 UTC, erikfTW commented on docs/knowledge_base/tips/skippable_tasks/index.md
> +<iframe width="640" height="360" src="https://www.taipy.io/wp-content/uploads/2023/04/full_config.mp4?_=1" frameborder="0" allowfullscreen></iframe>
It works!

2023-10-10 07:36 UTC, jrobinAV approved these changes

2023-10-10 07:36 UTC, merged