keywords proposal
Avaiga/taipy-doc pull request #675
Opened 2023-10-19 15:16 UTC by jrobinAV

I added a list of keywords for each kb_article. Here is the complete list:
```
gui, multi-page, vizelement, interactive, chart, navbar, layout, menu, input, text, button, state,
callback, on_change, table, part, expendable, scenario, task, datanode, configuration,
scenario_selector, dag, cycle, scope, job, job_execution, scenario_submission, standalone,
scenario_comparison, datanode_comparison, job_status, subscription, notify, markdown, storage_type,
file_selector, partials, dialog, pane, studio, dashboard, classification, optimization, ai, map,
notebook, deployment, stylekit, cloud
```

@FabienLelaquais @FlorianJacta @AlexandreSajus please review for each article the list of keywords used. Please do not hesitate to propose adding or removing keywords to some articles.

Once we agree on the keywords we can use some of them as a filter (not all of them 'cause we don't want to have to many filter values and we don't want a filter to display only one article).

@Jaufrey is it the right place to add keywords ? on the `<li>` tag?

2023-10-23 06:31 UTC, JaufreyTpy requested changes

2023-10-23 06:31 UTC, JaufreyTpy commented on docs/knowledge_base/index.md
> +  <li keywords="gui vizelement input text button chart navbar table layout part expandable menu state interactive multi-page callback on_change markdown">
`keywords` alone is note a valid HTML attribute. You must prefix custom attributes with `data-`. So it would be `data-keywords` instead.

2023-10-23 07:11 UTC, FabienLelaquais requested changes
Beside the obvious change on the attribute name...
I think this is far too detailed to be useful. And does not address the point: find what to use to do what. 'button' for example is not really helpful.
'dashboard' is good. People know what 'dashboard'-like applications are
'notebook' as well.


My proposal (note map- > maps):
gui, multi-page, layout, part, scenario, configuration, dag, cycle, scope, scenario_submission, standalone, scenario_comparison, subscription, storage_type, partials, studio, dashboard, classification, optimization, ai, maps, notebook, deployment, stylekit, cloud

If there are things that don't use any of those, we may want to extend it.

2023-10-23 13:30 UTC, jrobinAV commented on docs/knowledge_base/index.md
> +  <li keywords="gui vizelement input text button chart navbar table layout part expandable menu state interactive multi-page callback on_change markdown">
Done. Thx !

2023-10-23 13:33 UTC, JaufreyTpy approved these changes
👌

2023-10-23 14:06 UTC, AlexandreSajus approved these changes
It looks good to me. To answer Fabien's comment: I get the point, but "button" can still be helpful if I look for examples of how to use a button. Both proposed solutions are fine with me.

2023-10-23 15:40 UTC, jrobinAV commented
1. I removed the following keywords that I agree are either redundant or not necessary: 
```
interactive, input, text, date, number, button, on_change, expendable, job_status, job_execution, scenario_selector, file_selector, file_download, dialog, pane
```
For instance, `job_status` and `job_execution` are already covered by `job`. I believe that's enough. If someone is interested in `button` or `text`, he/she surely don't want to read a tutorial, a demo or a tip. He wants to read the doc.

However, I kept the following keywords that were not in your proposal @FabienLelaquais:
```
vizelement, menu, chart, navbar, state, callback, table, task, datanode, job, notify, markdown
```
They may have some interest. Let's talk about it later.

2023-10-24 07:59 UTC, FlorianJacta approved these changes

2023-10-24 13:10 UTC, merged

2023-10-24 13:11 UTC, jrobinAV commented
I am merging the PR now to unblock another PR on the topic. We can discuss and change the keywords later if needed.