Adding all new demos to release/3.0
Avaiga/taipy-doc pull request #777
Opened 2024-01-09 15:20 UTC by FlorianJacta

2024-01-09 16:02 UTC, jrobinAV reviewed
knowledge_base/index.md should also be updated.

2024-01-10 09:14 UTC, jrobinAV reviewed
To help the review, please generate the doc and check that:
- [x] The navigation panel is correct and contains all your new demos
- [x] The `knowledge_base` page is correct and contains all your new demos
- [x] The `knowledge_base/demos` page is correct and contains all your new demos
- [ ] The `knowledge_base/tutorials` page is correct and contains all your new tutotials
- [ ] The `knowledge_base/tips` page is correct and contains all your new tips
- [ ] Each new demo/tip/tuto page is correct, including the title, the sub-titles, the table of contents, and the links.
- [ ] Run Grammarly on the generated pages.

2024-01-10 09:17 UTC, FlorianJacta commented
I have some difficulty in building the doc. This was my plan. My problem is to fetch the release/3.0. I created the PR to see what is missing as files. The PR is currently not complete

2024-01-10 14:56 UTC, FlorianJacta commented
The card for 'fraud_detection' appears twice. I am trying to figure out how I did that. It appears twice in index.md of demos. Do you know how I can fix this?

2024-01-10 18:24 UTC, FabienLelaquais requested changes
A few blocking minor things...

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/background_remover.md
> +This one page demo uses rembg and [OpenCV library](https://opencv.org/) to remove the
```suggestion
This one page demo uses `rembg` and [the OpenCV library](https://opencv.org/) to remove the
```
A link to the rembg repo?

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/background_remover.md
> +1. **Upload Your Image:** Select an image that you want to remove the background; this
```suggestion
1. **Upload Your Image:** Select an image where you want to remove the background; this
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/background_remover.md
> +2. **More options:** Some parameters influences how the background is removed. These
```suggestion
2. **More options:** Some parameters influence how the background is removed. These
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/background_remover.md
> +parameters can be changed in the "More options" expandable.
```suggestion
parameters can be changed in the "More options" expandable section.
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/background_remover.md
> +4. **Download:** You can download the image through a button.
```suggestion
4. **Download:** You can download the image by pressing a button.
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/chatbot.md
> +This application allows the user to chat with GPT-3 by sending
A link to GPT?

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/drift_detection.md
> +(sex) columns. That is why we start by separating these columns first. Then, we run a statistical test
```suggestion
(sex) columns. That is why we start by separating these columns. Then, we run a statistical test 
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/drift_detection.md
> +Here, we are selecting data_big, a dataset similar to the dataset of reference but with rows with higher
```suggestion
Here, we are selecting *data_big*, a dataset similar to the dataset of reference but with rows with higher 
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/fraud_detection.md
> +# Understanding the Application
Skip a line after title (for readability and homogeneity)

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/fraud_detection.md
> + other transactions.
```suggestion
other transactions.
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/fraud_detection.md
> + above which a transaction is considered fraudulent. The user can choose the model according
```suggestion
above which a transaction is considered fraudulent. The user can choose the model according
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/fraud_detection.md
> +  to the displayed confusion matrix and by looking at False Positive and False Negative transactions.
```suggestion
to the displayed confusion matrix and by looking at false positive and false negative transactions.
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/chatbot.md
> +# Understanding the Application
Skip a line after title (for readability and homogeneity)

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/drift_detection.md
> +# Understanding the Application
Skip a line after title (for readability and homogeneity)

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/pollution_sensors.md
> +# Understanding the Application
Skip a line after title (for readability and homogeneity)

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/talk_to_taipy.md
> +# Understanding the Application
Skip a line after title (for readability and homogeneity)

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/demos/pollution_sensors.md
> +another server and sent to this Taipy app via a WebSocket. Taipy then processes the data and
```suggestion
another server and sent to this Taipy application via a WebSocket. Taipy then processes the data and 
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +- `context` is the initial context for the conversation, the LLM will use this to understand what behaviour is expected from it.
```suggestion
- *context* is the initial context for the conversation, the LLM will use this to understand what behavior is expected from it.
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +- `conversation` is a dictionary that will store the conversation history to be displayed
```suggestion
- *conversation* is a dictionary that stores the conversation history to be displayed.
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +- `current_user_message` is the current message that the user is typing
```suggestion
- *current_user_message* is the current message that the user is typing.
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +Create a function that takes as input a string `prompt` which
```suggestion
Create a function that takes as input the string stored in *prompt* which
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +        - state: The current state of the app.
```suggestion
        - state: The current state.
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +message. This function will add the user's message to the context,
```suggestion
message. This function adds the user's message to the context,
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +send it to the API, get the response, add the response to the
```suggestion
sends it to the API, gets the response, and adds the response to the
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +        - state: The current state of the app.
```suggestion
        - state: The current state.
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +[table](../../../manuals/gui/viselements/table.md_template) to display the
```suggestion
[table](../../../manuals/gui/viselements/table.md) to display the
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> + `conversation` dictionary and an
```suggestion
*conversation* dictionary and an
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> + [input](../../../manuals/gui/viselements/input) so that the
```suggestion
 [input](../../../manuals/gui/viselements/input.md) so that the
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> + the `send_message` function is triggered.
```suggestion
 the *send_message()* function is triggered.
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +    Gui(page).run(dark_mode=True, title="Taipy Chat")
```suggestion
    Gui(page).run(title="Taipy Chat")
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +The app's style is Taipy's default stylekit. We are going to
```suggestion
The application's style is Taipy's default Stylekit. We are going to
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +We now need to tell Taipy to apply these styles to the rows in
```suggestion
We now need to get Taipy to apply these styles to the rows in
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +the table. We'll first create a function that will return the
```suggestion
the table. We'll first create a function that returns the
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +        - state: The current state of the app.
```suggestion
        - state: The current state.
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +I have added notifications, a sidebar with a button to clear the conversation
"I"??

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +and a history of previous conversations. I won't go into the
"I"??

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +We are now going to deploy the app to Taipy Cloud so it is
```suggestion
We are now going to deploy the application to Taipy Cloud so it is
```

2024-01-10 18:24 UTC, FabienLelaquais commented on docs/knowledge_base/tutorials/chatbot/index.md
> +We can now deploy the app to Taipy Cloud:
Skip a line, or you won't get a proper bullet list

2024-01-11 11:43 UTC, jrobinAV commented on docs/knowledge_base/demos/background_remover.md
> +1. **Upload Your Image:** Select an image that you want to remove the background; this
"In which" instead of where or that.

2024-01-11 12:36 UTC, FabienLelaquais commented
> To help the review, please generate the doc and check that:
> 
> * [ ]  The navigation panel is correct and contains all your new demos
> * [ ]  The `knowledge_base` page is correct and contains all your new demos
> * [ ]  The `knowledge_base/demos` page is correct and contains all your new demos
> * [ ]  The `knowledge_base/tutorials` page is correct and contains all your new tutos
> * [ ]  The `knowledge_base/tips` page is correct and contains all your new tips
> * [ ]  Each new demo/tip/tuto page is correct, including the title, the sub-titles, the table of content, the links.

I would add... run Grammarly on the generated pages.

2024-01-16 13:37 UTC, FabienLelaquais approved these changes
👌

2024-01-16 13:37 UTC, merged