Adding articles PySpark and Decimator
Avaiga/taipy-doc pull request #796
Opened 2024-01-19 15:58 UTC by FlorianJacta

- Add PySpark article
- Add Decimator article
- Fix error 404 for Long Running Callbacks
- Change name of the Tutorial (Build a Complete app to First Realistic Application)
- Small changes on Databricks tip

Pre-built articles for PySpark and Decimator. Download and open it, you should be able to see the built version of the article:
[Articles Pre-built.zip](https://github.com/Avaiga/taipy-doc/files/13991384/Articles.Pre-built.zip)

![image](https://github.com/Avaiga/taipy-doc/assets/98709993/cc1d1848-c352-49c3-8b12-a756364144de)

![image](https://github.com/Avaiga/taipy-doc/assets/98709993/eb7e01b8-ac75-47ca-8ded-ce0401418676)

![image](https://github.com/Avaiga/taipy-doc/assets/98709993/068f29b3-ba7f-4c0e-b00a-5efd9fea539f)

![image](https://github.com/Avaiga/taipy-doc/assets/98709993/c91b9188-3e29-4207-906f-596da185df96)

2024-01-23 19:58 UTC, marisogo commented
Update image of databricks tips
![dbricks_img](https://github.com/Avaiga/taipy-doc/assets/120181423/eea4da84-ced2-48d7-a571-ed3c337c9037)

2024-01-25 07:51 UTC, jrobinAV commented on docs/knowledge_base/tips/databricks/index.md
> +Note that results and parameters are stringified. All JSON-compatible objects can be passed
```suggestion
Note that results and parameters are stringified. Only JSON-serializable objects can be passed 
```

2024-01-25 07:51 UTC, jrobinAV commented on docs/knowledge_base/tips/databricks/index.md
>  ## Scenarios and Databricks Integration
This should be a H1

2024-01-25 07:51 UTC, jrobinAV commented on docs/knowledge_base/tips/databricks/index.md
I would not make the steps as a title. Just a numerated list.

2024-01-25 07:51 UTC, jrobinAV commented on docs/knowledge_base/tips/decimator/index.md
![image](https://github.com/Avaiga/taipy-doc/assets/88036007/35235ba9-29d5-4a50-bbf0-10ad948044ce)
The table of content looks messy and not really readable

2024-01-25 10:04 UTC, FabienLelaquais requested changes
At least a typo to fix

2024-01-25 10:04 UTC, FabienLelaquais commented on docs/knowledge_base/tips/databricks/index.md
> +Here is an example of a Databrick Notebook where parameters are passed to the job
```suggestion
Here is an example of a DatabrickS Notebook where parameters are passed to the job 
```

2024-01-29 14:56 UTC, FabienLelaquais approved these changes
👍

2024-01-29 14:56 UTC, FabienLelaquais commented on docs/knowledge_base/tips/big_data_models/index.md
> +# Sample Application
Please skip a line after the title, like you did everywhere else. Homogeneity and clarity

2024-01-29 15:08 UTC, merged

2024-01-29 15:45 UTC, jrobinAV commented
Please delete the branch when it is not used anymore.