Fixed NameError in Multi-page Application Example
Avaiga/taipy-doc pull request #892
Opened 2024-03-29 08:45 UTC by Sven-Bo

Fixed variable names in the pages dictionary from `page1` and `page2` to `page_1` and `page_2` to resolve a NameError in the Taipy GUI multi-page application example.

2024-03-29 08:51 UTC, FlorianJacta approved these changes

2024-03-29 08:51 UTC, FlorianJacta commented
Nice one!

2024-03-29 08:53 UTC, FlorianJacta requested changes
Could you make this same PR on the Develop branch? The develop branch is the base branch of the repo. I will propagate the changes to release/3.1

2024-03-30 06:48 UTC, Sven-Bo commented
Closing this PR and opened a new one targeting `develop` as advised. See PR #893 . Thanks for the guidance!

2024-03-30 06:48 UTC, closed without merging