Styled Cards on user Manuals
Avaiga/taipy-doc pull request #955
Opened 2024-05-13 13:55 UTC by Satoshi-Sh

## Related Issue 
Fixed #899  

## Updates 
- Added colors to the two cards 
- Removed the Read More section

## Screenshot 
![Screenshot from 2024-05-13 08-49-45](https://github.com/Avaiga/taipy-doc/assets/73622805/7c3698d5-3df4-49d5-b1ea-af92bad921b5)

2024-05-13 14:34 UTC, FlorianJacta requested changes
I think it should like the other cards here with white SVGs. What do you think?
```
  <div class="tp-col-12 tp-col-md-6 d-flex">
    <a class="tp-content-card tp-content-card--beta" href="../gui/viselements/index.md">
      <header class="tp-content-card-header">
        <img class="tp-content-card-icon--small" src="../../images/icons/visual-element-??.svg">
        <h3>Visual elements</h3>
      </header>
      <div class="tp-content-card-body">
        <p>
          Browse dozens of Taipy GUI controls to build your UI.
        </p>
      </div>
    </a>
  </div>
```

2024-05-13 15:33 UTC, Satoshi-Sh commented
> I think it should be like the other cards here with white SVGs. What do you think? Something along those lines
> 
> ```
>   <div class="tp-col-12 tp-col-md-6 d-flex">
>     <a class="tp-content-card tp-content-card--beta" href="../gui/viselements/index.md">
>       <header class="tp-content-card-header">
>         <img class="tp-content-card-icon--small" src="../../images/icons/visual-element-??.svg">
>         <h3>Visual elements</h3>
>       </header>
>       <div class="tp-content-card-body">
>         <p>
>           Browse dozens of Taipy GUI controls to build your UI.
>         </p>
>       </div>
>     </a>
>   </div>
> ```

White SVGs look better.

![white-svg](https://github.com/Avaiga/taipy-doc/assets/73622805/cc987981-07ce-4bac-a809-f0f227e31484)

2024-05-13 16:11 UTC, FlorianJacta commented
Looks great! Is it not in a row because it is in mobile view?

2024-05-13 16:34 UTC, Satoshi-Sh commented
It's just because of the window width. If the window is wider, they come to side by side.

![Screenshot from 2024-05-13 11-33-23](https://github.com/Avaiga/taipy-doc/assets/73622805/d099984d-bb03-4d6d-93f7-6865bda4937a)

2024-05-14 07:52 UTC, FlorianJacta approved these changes
Great job!

2024-05-14 07:53 UTC, merged

2024-05-14 08:45 UTC, FlorianJacta commented
It has been merged however the "Visual elements" card leads to a 404 error. 

https://docs.taipy.io/en/develop/manuals/usermans/

It is not your fault. This issue was also present in the 3.1. Do you want to take this issue as you worked on it?

2024-05-14 11:37 UTC, Satoshi-Sh commented
@FlorianJacta Thanks for reviewing my PR. I made an issue about it already. #953

2024-05-14 11:46 UTC, FlorianJacta commented
Oh great, I will close mine then.