Add fullwidth description to file_selector and file_download
Avaiga/taipy-doc pull request #984
Opened 2024-06-11 14:03 UTC by Satoshi-Sh

## Related Issue 
Fixed #981
## Updates 
- Added fullwidth description to the file_selector and file_download templates.

2024-06-12 07:31 UTC, FlorianJacta commented
It seems great. Do you have a screenshot to see what the documentation will look like? (I am speaking about the documentation, not the *file_selector*)

2024-06-12 11:15 UTC, Satoshi-Sh commented
Here is the screenshot.

![Screenshot from 2024-06-12 06-13-51](https://github.com/Avaiga/taipy-doc/assets/73622805/15eefe1d-46e8-4bab-930a-c66bd3ccfe14)

2024-06-12 13:04 UTC, FlorianJacta commented
Fantastic work! Like the other PR, as it touches the User Manual, it is blocked by this PR https://github.com/Avaiga/taipy-doc/pull/940

But once merged, we can merge this PR also.

You did a great job as always!

2024-06-12 13:13 UTC, Satoshi-Sh commented
Glad to hear that. Thanks for the guidance, Florian.

2024-06-17 10:37 UTC, FabienLelaquais requested changes
Please update the doc template files.

2024-06-17 10:37 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/file_download.md_template
> +The [Stylekit](../styling/stylekit.md) provides a specific class that you can use to style date selectors:
```suggestion
The [Stylekit](../styling/stylekit.md) provides a specific class that you can use to style file download elements:
```

2024-06-17 10:37 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/file_download.md_template
> +    If a date selector uses the *fullwidth* class, then it uses the whole available
```suggestion
    If a file download element uses the *fullwidth* class, then it uses the whole available
```

2024-06-17 10:37 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/file_selector.md_template
> +The [Stylekit](../styling/stylekit.md) provides a specific class that you can use to style date selectors:
```suggestion
The [Stylekit](../styling/stylekit.md) provides a specific class that you can use to style file selectors:
```

2024-06-17 10:37 UTC, FabienLelaquais commented on docs/manuals/gui/viselements/file_selector.md_template
> +    If a date selector uses the *fullwidth* class, then it uses the whole available
```suggestion
    If a file selector uses the *fullwidth* class, then it uses the whole available
```

2024-06-17 10:39 UTC, FabienLelaquais commented
The issue was unblocked for it does not impact the manuals refactoring.

2024-07-10 07:50 UTC, FlorianJacta approved these changes

2024-07-10 08:04 UTC, FabienLelaquais approved these changes
👍

2024-07-10 08:07 UTC, merged

2024-07-10 08:08 UTC, jrobinAV commented
blocked by #709